## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
value_counts = application_df['APPLICATION_TYPE'].value_counts()
cutoff_value = 500
application_types_to_replace = value_counts[value_counts < cutoff_value].index.tolist()
if len(application_types_to_replace) > 0:
    application_types_to_replace.append('Other')
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
name_count = application_df['NAME'].value_counts()
name_count

NAME
PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: count, Length: 19568, dtype: int64

In [7]:
#Process Names for binning
name_cutoff_value = 10
names_to_replace = name_count[name_count < name_cutoff_value].index.tolist()
if len(names_to_replace) > 0:
    names_to_replace.append('Other')
# Replace in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

NAME
Other                                      21022
PARENT BOOSTER USA INC                      1260
TOPS CLUB INC                                765
UNITED STATES BOWLING CONGRESS INC           700
WASHINGTON STATE UNIVERSITY                  492
                                           ...
CASCADE 4-H FOUNDATION                        10
FREE & ACCEPTED MASONS OF WASHINGTON          10
NEW MEXICO GARDEN CLUBS INC                   10
NATIONAL ASSOCIATION OF HISPANIC NURSES       10
UNION OF CALIFORNIA STATE WORKERS             10
Name: count, Length: 223, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
filtered_classifications = classification_count[classification_count > 1]
filtered_classifications

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 100
classifications_to_replace = classification_count[classification_count < cutoff_value].index.tolist()
if len(classifications_to_replace) > 0:
    classifications_to_replace.append('Other')

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_encoded = pd.get_dummies(application_df)
print(application_df_encoded.head())

   STATUS  ASK_AMT  IS_SUCCESSFUL  NAME_ACE MENTOR PROGRAM OF AMERICA INC  \
0       1     5000              1                                   False
1       1   108590              1                                   False
2       1     5000              0                                   False
3       1     6692              1                                   False
4       1   142590              1                                   False

   NAME_AIR FORCE ASSOCIATION  NAME_ALABAMA FEDERATION OF WOMENS CLUBS  \
0                       False                                    False
1                       False                                    False
2                       False                                    False
3                       False                                    False
4                       False                                    False

   NAME_ALABAMA TREASURE FOREST ASSOCIATION  NAME_ALPHA PHI SIGMA  \
0                                     False                 False
1                                     False                 False
2                                     False                 False
3                                     False                 False
4                                     False                 False

   NAME_ALPHA PHI SIGMA INC  NAME_ALTRUSA INTERNATIONAL FOUNDATION INC  ...  \
0                     False                                      False  ...
1                     False                                      False  ...
2                     False                                      False  ...
3                     False                                      False  ...
4                     False                                      False  ...

   INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0              False                   False                     False
1               True                   False                     False
2              False                   False                     False
3              False                    True                     False
4              False                   False                      True

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0               False             False                   False
1               False             False                   False
2               False             False                   False
3               False             False                   False
4               False             False                   False

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0            False              False                      True
1            False              False                      True
2            False              False                      True
3            False              False                      True
4            False              False                      True

   SPECIAL_CONSIDERATIONS_Y
0                     False
1                     False
2                     False
3                     False
4                     False

[5 rows x 273 columns]

In [12]:
# Split our preprocessed data into our features and target arrays
X = application_df_encoded.drop(columns=['IS_SUCCESSFUL'])
y = application_df_encoded['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=78)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=90, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=20, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 90)                24570

 dense_1 (Dense)             (None, 20)                1820

 dense_2 (Dense)             (None, 1)                 21

=================================================================
Total params: 26411 (103.17 KB)
Trainable params: 26411 (103.17 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Train the model
fit_nn = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.4722 - accuracy: 0.7722
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4453 - accuracy: 0.7836
Epoch 3/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4412 - accuracy: 0.7854
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4387 - accuracy: 0.7853
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4368 - accuracy: 0.7874
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4355 - accuracy: 0.7881
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4345 - accuracy: 0.7876
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4329 - accuracy: 0.7900
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4325 - accuracy: 0.7907
Epoch 10/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4319 - accuracy: 0.7908
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4309 - accuracy: 0.7907
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4301 - accuracy: 0.7921
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4294 - accuracy: 0.7906
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4293 - accuracy: 0.7928
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4286 - accuracy: 0.7931
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4282 - accuracy: 0.7936
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4275 - accuracy: 0.7940
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4268 - accuracy: 0.7931
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4270 - accuracy: 0.7943
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4258 - accuracy: 0.7950
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4254 - accuracy: 0.7953
Epoch 22/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4248 - accuracy: 0.7954
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4247 - accuracy: 0.7956
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4246 - accuracy: 0.7955
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4243 - accuracy: 0.7947
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4238 - accuracy: 0.7952
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4234 - accuracy: 0.7953
Epoch 28/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4234 - accuracy: 0.7955
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4229 - accuracy: 0.7964
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4227 - accuracy: 0.7970
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4226 - accuracy: 0.7967
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4218 - accuracy: 0.7971
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4220 - accuracy: 0.7962
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4213 - accuracy: 0.7965
Epoch 35/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4209 - accuracy: 0.7975
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4215 - accuracy: 0.7978
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4209 - accuracy: 0.7978
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4210 - accuracy: 0.7973
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4206 - accuracy: 0.7968
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4201 - accuracy: 0.7974
Epoch 41/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4205 - accuracy: 0.7978
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4207 - accuracy: 0.7975
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4200 - accuracy: 0.7975
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4196 - accuracy: 0.7966
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4192 - accuracy: 0.7977
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4195 - accuracy: 0.7984
Epoch 47/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4191 - accuracy: 0.7981
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4190 - accuracy: 0.7982
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4183 - accuracy: 0.7991
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4190 - accuracy: 0.7985
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4186 - accuracy: 0.7991
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4180 - accuracy: 0.7982
Epoch 53/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4181 - accuracy: 0.7984
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4177 - accuracy: 0.7990
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4182 - accuracy: 0.7981
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4177 - accuracy: 0.7981
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4176 - accuracy: 0.7989
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4175 - accuracy: 0.7981
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4174 - accuracy: 0.7989
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4170 - accuracy: 0.7984
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4175 - accuracy: 0.7982
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4171 - accuracy: 0.7984
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4169 - accuracy: 0.7986
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4168 - accuracy: 0.7979
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4172 - accuracy: 0.7976
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4164 - accuracy: 0.7979
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4171 - accuracy: 0.7978
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4162 - accuracy: 0.7988
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4164 - accuracy: 0.7987
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4161 - accuracy: 0.7984
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4162 - accuracy: 0.7991
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4163 - accuracy: 0.7989
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4162 - accuracy: 0.7986
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4161 - accuracy: 0.7996
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4157 - accuracy: 0.7987
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4159 - accuracy: 0.7987
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4159 - accuracy: 0.7999
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4160 - accuracy: 0.7987
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4157 - accuracy: 0.7994
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4154 - accuracy: 0.8003
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4154 - accuracy: 0.7991
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4153 - accuracy: 0.7990
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4155 - accuracy: 0.7994
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4157 - accuracy: 0.7992
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4149 - accuracy: 0.7996
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4155 - accuracy: 0.7995
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4151 - accuracy: 0.7998
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4150 - accuracy: 0.7998
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4150 - accuracy: 0.7993
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4150 - accuracy: 0.7996
Epoch 91/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4143 - accuracy: 0.7995
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4149 - accuracy: 0.7991
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4145 - accuracy: 0.7991
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4151 - accuracy: 0.8000
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4146 - accuracy: 0.7994
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4145 - accuracy: 0.7999
Epoch 97/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4148 - accuracy: 0.7994
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4145 - accuracy: 0.7994
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4144 - accuracy: 0.7992
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4140 - accuracy: 0.7995

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 [==============================] - 1s 2ms/step - loss: 0.4646 - accuracy: 0.7825
Loss: 0.46458321809768677, Accuracy: 0.7825073003768921

In [17]:
# Export our model to HDF5 file
model_filename = 'AlphabetSoupCharity_Optimization.h5'
nn.save(model_filename)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(